import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";


const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"], // include bold weights
  variable: "--font-inter",
  display: "swap",
});

import { Lexend } from 'next/font/google';
import NavbarAdmin from "./components/admin/Navbar";
import { Toaster } from "react-hot-toast";

const lexend = Lexend({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700', '900'],
  variable: '--font-lexend',
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lexend.variable} font-display`}>
        {/* <Navbar /> */}
        <NavbarAdmin/>
        {children}
        <Toaster position="top-right" reverseOrder={false} />
      </body>
    </html>
  );
}
