import "./globals.css";
import Navbar from "./components/Navbar";


import { Lexend } from 'next/font/google';
import { Toaster } from "react-hot-toast";
import Providers from "./providers";

const lexend = Lexend({
  subsets: ['latin'],
  weight: ['300', '400', '500', '700', '900'],
  variable: '--font-lexend',
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lexend.variable} font-display`}>
        <Navbar />
      <Providers >
        {children}
      </Providers>
        <Toaster position="top-right" reverseOrder={false} />
      </body>
    </html>
  );
}
